understandable-machine-intelligence-lab/Quantus

- quantus/metrics/localisation_metrics.py
Edit in pointing game where the masks are assumed to be square and reshaped. This can cause problems if the masks are non-square. This edit removes the reshape. Since we are flattening the masks the reshape should not be necessary and the non-square issue should be resolved.
> Edit reshape of mask in pointing game

- README.md
- quantus/metrics/faithfulness_metrics.py
- tutorials/tutorial_basic_example_all_metrics.ipynb
Apart from a small typo regarding `requirements_test.txt` in the `README.md`, `RegionPerturbation` had a wrong citation. I fixed it both in the python-file and the ipython-notebook.
I subsequently removed the `text_warning` attribute, which was already unused before my changes.
I don't know if the code relevant for this attribute in `attributes_check` and `set_warn` in `asserts.py` is now necessary anymore, but you will definitely know better.
> minor typo corrections

- quantus/helpers/explanation_func.py
- tests/helpers/test_explanation_func.py
Having a baseline explanation that you know should be "bad" can in many cases be a good sanity check. The current baselines 'Control Var. Constant' and 'Control Var. Sobel Filter', can run into problems for perturbation-based metrics, since they often don't change under perturbation. The baseline added in this PR is simply a random explanation sample from U(0, 1), entitled 'Control Var. Random Uniform'.
> Added a random uniform explanation method

- requirements.txt
Poetry version solving currently fails at `poetry add quantus` because:
`opencv-python (4.5.5.62)` depends on `numpy (>=1.21.2)` and Quantus has locked `numpy==1.19.5`.
Instead, replacing `==` with `>=` solves the issue.
> Require `numpy>=1.19.5` for correct version solving

- quantus/helpers/utils.py
This is a quick-fix to the problem that when tensorflow isn't installed, running the line `if isinstance(model, tf.keras.Model)`
gives the following error:
`NameError: name 'tf' is not defined`
> bug: tensorflow is required, even if not used

- quantus/helpers/utils.py
Added a small suggestion in error message thrown by for example `quantus.evaluate` if it cannot determine channel-order. Using metrics directly, its easier to observe that such a parameter exists, such as [here](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/ec43ca80d83244c8e55f4600135b0d9c931f8447/quantus/metrics/localisation/pointing_game.py#L118)
> improve error message

- quantus/evaluation.py
version: 0.3.0
`quantus.evaluate` now throws the following error for default value of `explain_func_kwargs = None`:
```
TypeError: 'NoneType' object is not a mapping
```
The error happens when `explain_func_kwargs` is unpacked at [L:105](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/ec43ca80d83244c8e55f4600135b0d9c931f8447/quantus/evaluation.py#L105)
A quick fix is setting `explain_func_kwargs = dict()` if its None.
@annahedstroem
> bug: default value of explain_func_kwargs cannot be unpacked.

- .github/workflows/python-package.yml
- quantus/helpers/utils.py
- quantus/metrics/faithfulness/pixel_flipping.py
- Enable the user to return an AUC score instead of a PixelFlipping curve
- Changes in `pixel_flipping.py` script
- All tests pass
> Added AUC calculation to Pixel-Flipping

- quantus/metrics/faithfulness/irof.py
- During IROF computation, perturbation of subsequent segments should be accumulated. Until now, segments were perturbated one by one. Hence, incorrect AOC values were returned. 
- Default segmentation function "slic" assign numbers for superpixel starting from 0, which makes existing `len(np.unique(segments))` miss one segment.
> Fix IROF metric - perturbation accumulation and counting the segments

- quantus/helpers/warn.py
The previous implementation of `warn_perturbation_caused_no_change` raises a warning if **any** element of the perturbed input **differs** from the original input. This behaviour contradicts the function name. Additionally, comparing floats with the `==` operator can be problematic (false negatives) due to error accumulation during float operations.
After this fix, warnings about no change in perturbation won't be raised if there has actually been a change in input. Moreover, the condition for raising the warning handles floats well by using `np.allclose`.
> Fix warn_perturbation_caused_no_change

- setup.py
> updated setuÃp.py with absolute path

- quantus/functions/similarity_func.py
- quantus/helpers/constants.py
- requirements_test.txt
- tests/conftest.py
- tests/helpers/test_similarity_func.py
> Review distance metrics and added squared distance as measure

- quantus/py.typed
- Quantus uses inline type-hints, `py.typed` is a marker specifying, that package is typed. 
- More about it here [EP 484](https://peps.python.org/pep-0484). 
- In nutshell, adding this will make mypy scan type hints exported by Quantus.
No breaking changes expected.
> Add py.typed

- quantus/metrics/robustness/avg_sensitivity.py
- quantus/metrics/robustness/max_sensitivity.py
Issue addressed: https://github.com/understandable-machine-intelligence-lab/Quantus/issues/288.
> Fixed issue in max_sensitivity.py

- .github/workflows/python-package.yml
- pyproject.toml
- quantus/__init__.py
- Fix for the installation problem https://github.com/understandable-machine-intelligence-lab/Quantus/issues/292, which was introduced in https://github.com/understandable-machine-intelligence-lab/Quantus/pull/291
To sum up, the `__version__` must be defined in top-level `__init__.py` as a string literal, 
then it will be dynamically fetched by `flit` during packaging stage.
> dynamic version fix

- quantus/functions/explanation_func.py
- quantus/helpers/model/tf_model.py
- tests/metrics/test_localisation_metrics.py
- Fixing issue: https://github.com/understandable-machine-intelligence-lab/Quantus/issues/304
> Fix channels first issue

- quantus/metrics/randomisation/mprt.py
- Added a warning for renamed metric argument
> Add warning of deprecated argument (handle elegantly)

- quantus/functions/explanation_func.py
- tests/functions/test_explanation_func.py
> Bugfixes tabular data on explanation_func.py

- pyproject.toml
- quantus/helpers/model/pytorch_model.py
- tests/conftest.py
- tests/functions/test_pytorch_model.py
- tox.ini
- This PR adds an initial implementation for the HuggingFace SequenceClassification model with some initial functionality. I also organized imports using [isort](https://pypi.org/project/isort/) and made a few adjustments to increase flake8 compliance
This should be taken as an initial step toward: #238, #103, and #217 
- Insert a description of the changes implemented in the pull request.
- @mentions of the person that is apt to review these changes, e.g., @annahedstroem
> Integrate AutoModelForSequenceClassification through PytorchModel

- .github/workflows/python-package.yml
- README.md
- docs/source/getting_started/installation.md
- pyproject.toml
- tox.ini
- Remove py3.7 support
- https://github.com/understandable-machine-intelligence-lab/Quantus/issues/302
- Additionally, e.g. running `pip install .[tests]` would print 
```
WARNING: quantus 0.5.3 does not provide the extra 'tf-explain'
```
changing the marker from `tf_explain` to `tf-explain` solved the issue, however I don't have an explanation why it has occurred in the first place 🤷
> * drop py37 support

- quantus/helpers/model/pytorch_model.py
- Fixing isinstance(..., None) which causes syntaxerror
> small bugfix pytorch_model.py
