understandable-machine-intelligence-lab/Quantus

README.md

updating readme to reflect arxiv submission

---

README.md
quantus/evaluation.py
quantus/helpers/asserts.py
quantus/helpers/explanation_func.py
quantus/helpers/perturb_func.py
quantus/helpers/plotting.py
quantus/helpers/similar_func.py
quantus/helpers/tf_model.py
quantus/helpers/utils.py
quantus/helpers/warn_func.py
quantus/metrics/axiomatic_metrics.py
quantus/metrics/complexity_metrics.py
quantus/metrics/faithfulness_metrics.py
quantus/metrics/localisation_metrics.py
quantus/metrics/randomisation_metrics.py
quantus/metrics/robustness_metrics.py
setup.py
tests/fixtures.py
tests/helpers/test_utils.py
tests/metrics/test_faithfulness_metrics.py
tests/test_evaluation.py

Issue fixed: https://github.com/understandable-machine-intelligence-lab/Quantus/issues/110

Issues #55 #104, #106, #110 and #113: smaller bug fixes

---

quantus/helpers/explanation_func.py

Fixing Issue: [Bug] NameError: name 'tf' is not defined #119

Fix typing issue explanation_func.py

---

quantus/helpers/utils.py

Lets hope the automatic tests don't fail :)

Fixed a bug with patch creation and with .index() on np arrays

---

quantus/metrics/axiomatic_metrics.py
quantus/metrics/complexity_metrics.py
quantus/metrics/faithfulness_metrics.py
quantus/metrics/localisation_metrics.py
quantus/metrics/randomisation_metrics.py
quantus/metrics/robustness_metrics.py

Using `tqdm.auto.tqdm` will produce different progress bars, when running in jupyter, and in CLI

use auto tqdm

---

docs/source/docs_api/quantus.helpers.functions.discretise_func.rst
docs/source/docs_api/quantus.helpers.functions.explanation_func.rst
docs/source/docs_api/quantus.helpers.functions.loss_func.rst
docs/source/docs_api/quantus.helpers.functions.mosaic_func.rst
docs/source/docs_api/quantus.helpers.functions.norm_func.rst
docs/source/docs_api/quantus.helpers.functions.normalise_func.rst
docs/source/docs_api/quantus.helpers.functions.perturb_func.rst
docs/source/docs_api/quantus.helpers.functions.rst
docs/source/docs_api/quantus.helpers.functions.similarity_func.rst
docs/source/docs_api/quantus.helpers.model.model_interface.rst
docs/source/docs_api/quantus.helpers.model.models.rst
docs/source/docs_api/quantus.helpers.model.pytorch_model.rst
docs/source/docs_api/quantus.helpers.model.rst
docs/source/docs_api/quantus.helpers.model.tf_model.rst
docs/source/docs_api/quantus.helpers.rst
docs/source/docs_api/quantus.helpers.warn.rst
docs/source/getting_started/installation.md

- Refactored installation options. E.g., "extras" is removed, instead singular XAI libraries are targetable.

Installation option refactoring to be more concise

---

quantus/helpers/utils.py
tutorials/Tutorial_Getting_Started_with_Tabular_Data.ipynb

- Notebook based on Titanic data
- Minimal example
- 
- Small changes to utils to make it work.

Tabular data notebook

---

requirements.txt

- Remove coverage>=6.2 dependency from requirements.txt
- Removed package
- All tests pass

Remove coverage>=6.2

---

CITATION

- Fixed citation file 
- Only concerned the citation file
- Adhere to CFF (citation file format) specification

Citation fixes

---

README.md
quantus/functions/explanation_func.py
tutorials/Tutorial_Explore_Explanation_Wrappers.ipynb
tutorials/Tutorial_Getting_Started.ipynb
tutorials/Tutorial_Getting_Started_with_Tabular_Data.ipynb
tutorials/Tutorial_Getting_Started_with_Tensorflow.ipynb
tutorials/Tutorial_Getting_Started_with_Time_Series_Data.ipynb
tutorials/Tutorial_Handle_Changes_In_Predictions.ipynb
tutorials/Tutorial_ImageNet_Example_All_Metrics.ipynb
tutorials/Tutorial_ImageNet_Quantification_with_Quantus.ipynb
tutorials/Tutorial_Metric_Parameterisation_Analysis.ipynb
tutorials/Tutorial_NLP_Demonstration.ipynb
tutorials/Tutorial_XAI_Sensitivity_Model_Training.ipynb
tutorials/assets/titanic3.csv

- Tabular data notebook fixes
- Binder badges

Tutorial fixes

---

.github/workflows/python-package.yml
tests/conftest.py

Action fixes

---

.github/workflows/python-publish.yml

- Targeted file `python-publish.yml`

Updated python publish script

---

MANIFEST.in

add reqs via MANIFEST.ini

---

quantus/__init__.py

new release 0.4.4

---

quantus/metrics/base.py

Unifying PR release v0.4.5

---

quantus/metrics/randomisation/smooth_mprt.py

- Small fixes related to warning.

Mprt metrics

---

quantus/metrics/randomisation/smooth_mprt.py

- Insert a clear and concise description of what the PR is about.
- Optionally, make a reference to an existing [issue](https://github.com/understandable-machine-intelligence-lab/Quantus/issues).
- Describe the expected improvements of Quantus that results from this PR. Why was this work completed?
- Insert a description of the changes implemented in the pull request.

add back sys typo

---

pyproject.toml
quantus/metrics/randomisation/mprt.py

Update pandas version control and warn message for Model Parameter Randomisation Test

---

quantus/metrics/randomisation/efficient_mprt.py
quantus/metrics/randomisation/mprt.py
quantus/metrics/randomisation/smooth_mprt.py

- Fixing indent error, only looping through the last layer.
- See three files

fixing indent error

---

quantus/__init__.py

New release 0.5.2 bugfix

---

pyproject.toml

- Easy fix to: https://github.com/TvoroG/pytest-lazy-fixture/issues/65

fixing pytest compatibility bug

---

pyproject.toml
quantus/helpers/model/pytorch_model.py

- Insert a clear and concise description of what the PR is about.
- Optionally, make a reference to an existing [issue](https://github.com/understandable-machine-intelligence-lab/Quantus/issues).
- Describe the expected improvements of Quantus that results from this PR. Why was this work completed?
- Insert a description of the changes implemented in the pull request.

Include Module verification and clean pyproject.toml

---

quantus/helpers/plotting.py

See Issue Description #352 
Solution:
If input results is not a dictionary, check for dimensionality. If multi-dimensional (batch_size, perturbation steps), meaning it contains results for more than one image, then select the perturbation steps.
```
else:
if np.ndim(results) == 1:
plt.plot(np.arange(0, len(results)), results)
else:
plt.plot(np.arange(0, np.shape(results)[1]), np.mean(results, axis=0))
```

Closing Issue #352, Fixing Region Perturbation Plotting

---

quantus/metrics/robustness/relative_input_stability.py

Updated name typo 
